### ISSUE TITLE
Modify CI workflow to run affected:e2e

### ISSUE THREAD

**Issue by TapaiBalazs** [thisdot/open-source#129]
We now have two demoapps and two sets of e2e tests.
One demoapp is an angular demoapp, the other one is a vue demoapp.

I don't want to run vue e2e tests when I make changes in an angular library, and I don't want to run angular e2e tests when I make changes in a vue-only library.

The goal of this task is to modify the CI workflow to run NX's built in `affected` command in CI

**Comment by ahmedsilat44** [comment]
I found this in the docs 
![image](https://user-images.githubusercontent.com/105588821/195657451-bc0ac96d-5892-4a30-860f-b22dbd59ab18.png)
I am not sure how to implement this though. If you can guide me through it I would like to work on this issue.

**Comment by ahmedsilat44** [comment]
I have created this pull request with the changes, that according to the Nx Documentation will work.
