### ISSUE TITLE
"Movements" a VSCode extension to cursor movements like word jumps and relative line goto

### ISSUE THREAD

**Issue by NachoVazquez** [thisdot/open-source#134]
**What is the project?**

It is a VSCode extension that enables users to improve their keyboard usage by adding cursor movements that do not exist on VSCode by default.

**Where did the idea come from?**

The https://github.com/Enkel-Digital/relativity extension allows making relative line goto actions in VSCode. I use it every day but there were some limitations that I wanted to fix. After checking the GitHub repository I noticed that it had some of the fixes that I needed but those changes were never released. It has been 2 years since the last time it was updated so it is fair to consider it abandoned. My idea is to reuse what they had and continue working over that base.

**How long will it take to build? What milestones exist (if applicable)?**

Since most of the base features are already there, the next milestone would be to add tests to the existing code (it has none), fix some little issues that I observed, and create the word jump functionality.

I would estimate:
- 8 hours to migrate the code and get used to VSCode extensions development, I have no previous experience.
- 8 hours to add the unit tests for the previous functionality
- 6 hours to build and test the jump words feature (at this point I would have more knowledge on the topic)

**Comment by dustinsgoodman** [comment]
Discussed in slack but we are not going to pursue this idea.
