### ISSUE TITLE
Nx-Vite plugin

### ISSUE THREAD

**Issue by BigAB** [thisdot/open-source#139]
## What do you want to build?

I would like to build an Nx-Plugin for adding and running Vite projects and libraries to an Nx Monorepo.

## Where did your idea come from?

I have previously worked on a project where we used [Nx](https://nx.dev/) and [Vite](https://vitejs.dev/), and we wrote a workspace plugin with Vite `executors` for building and serving our Vite libraries and MFE playground.

Though there are quite a few community Nx Plugins for Vite, none of them seem "finished" or work very well, so I think there is an opportunity to pave this path and maybe influence Nrwls "official" implementation with ours if they go in that direction.

### Milestone 1 - MVP (0.1 release)

A base minimum for a public Nx-Vite Plugin would require:

- an nx `executor` for each of the Vite commands (`dev`, `preview`, `build`)
- a nx `generator` for a generic Vite "app"
- an nx `generator` for a generic Vite "lib"

I can't give accurate estimates at all at this stage, but a wild guess that may be far too short or far too long is probably better than nothing so...

**Est Time: 15hrs**

### Milestone 2 - Vitest + React + Preset  (1.0 release)

Assuming the `executors` from the first milestone do not require any new features, the next step towards a general "release" would require:

- a [Vitest](https://vitest.dev/) `generator` integrated with the `app` and `lib` generators, so that Vitest tests are included by default
-  a React `generator` integrated with the `app` and `lib` generators, so a user can choose to generate a React "app" or "lib" powered by Vite
- an Nx **preset** `generator` which allows our plugin to be used as a customization option when creating a new workspace with `npx create-nx-workspace --preset=@thisdotlabs/nx-vite`

Again, I don't think I can give accurate estimates at all, but...

**Est Time: 15hrs**

### Milestone 2 - Vite Storybook  (1.1 release)

- a [Vite Storybook](https://storybook.js.org/docs/html/builders/vite) `generator` integrated with the `app` and `lib` generators, so that Vite libs and apps can have a Vite-Storybook integration set up for them

**Est Time: 8hrs**

**Comment by dustinsgoodman** [comment]
Repeating from Slack - let's do as follows:

- Milestone 1 is approved to execute and for future evaluation
- We should consider release strategy: blog post + tweets. Maybe a JS Drop too?
- If possible, we should look at a milestone to update our other apps in our oss repo to use this plugin. @TapaiBalazs will know more about the feasibility here of doing this.

**Comment by BigAB** [comment]
So the Nx team [has decided to make a `@nrwl/vite` plugin](https://github.com/nrwl/nx/discussions/12836) as one of the foundational plugins (like `@nrwl/cypress` or `@nrwl/rollup`) so this project is pretty much dead in the water.
