### ISSUE TITLE
Update contribution guideline

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/open-source#32]
We need to update the language in https://github.com/thisdot/open-source/blob/main/CONTRIBUTING.md. See https://docs.google.com/document/d/1iJFkuf1jNOOqh79qsegiy-SgQDoV61PJ_3FQNXjObJI/edit for details.

**Comment by TapaiBalazs** [comment]
@dustinsgoodman I cannot see any difference between the current contribution.md file and that google document. Are you sure you saved your version, or added the comments there?
